version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Geslo123
      MYSQL_DATABASE: user
      MYSQL_USER: root
      MYSQL_PASSWORD: Geslo123
    ports:
      - "3306:3306"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
