name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          DB_DATABASE: test_db
          DB_USER: root
          DB_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for database to be ready
        run: |
          sleep 15  # wait for MySQL to initialize

      - name: Run tests
        env:
          DB_DATABASE: test_db
          DB_USER: root
          DB_PASSWORD: root
        run: |
           pytest --maxfail=1 --disable-warnings

