name: Run Tests

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor, e.g., 'master', 'dev', etc.
  pull_request:
    branches:
      - main  # If you want tests to run on pull requests as well

jobs:
  test:
    runs-on: ubuntu-latest  # You can also choose 'windows-latest' or 'macos-latest' depending on your needs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Change this to the version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # This runs your tests
