name: Run Tests

on:
  push:
    branches:
      - '*'  # Change to the branch you want to monitor, e.g., 'master', 'dev', etc.
  pull_request:
    branches:
      - '*'  # If you want tests to run on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Use the secret for the password
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}  # Use the secret for the database name
        ports:
          - 3306:3306  # Expose the MySQL port
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DB_HOST=localhost" >> $GITHUB_ENV  # Set the MySQL host
        echo "DB_USER=root" >> $GITHUB_ENV  # Set the MySQL user
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV  # Use the secret for the password
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV  # Use the secret for the database name

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e 'SELECT 1'; do
          echo "Waiting for MySQL to be ready..."
          sleep 3
        done

    - name: Run tests
      run: |
        pytest
