name: Run Tests

on:
  push:
    branches:
      - '*'  # Change to the branch you want to monitor, e.g., 'master', 'dev', etc.
  pull_request:
    branches:
      - '*'  # If you want tests to run on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
