name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SQLite in-memory database
        run: |
          echo "DATABASE_URL=sqlite:///:memory:" >> $GITHUB_ENV  # Set SQLite in-memory database URL

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Check environment variables
        run: |
          echo "DATABASE_URL=${DATABASE_URL}"

      - name: Wait for SQLite to be ready
        run: |
          # SQLite is in-memory, so no waiting is required
          echo "SQLite database is ready"

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
