name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    services:
      mysql:
        image: mysql:8.0  # Using MySQL 8.0 for database service
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Set MySQL root password
          MYSQL_DATABASE: testdb  # Set up the database name
        ports:
          - 3306:3306  # Expose MySQL port
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python 3.9
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements.txt
        pip install pytest  # Install pytest for running tests

    # Wait for MySQL to be ready
    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h "localhost" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    # Run database migrations or setup (e.g. creating tables if needed)
    - name: Set up database
      run: |
        python -c "from app.core.database import init_db; init_db()"  # Run database setup scripts

    # Run tests with pytest
    - name: Run tests
      run: |
        pytest tests/test_user.py  # Run specific test file or all tests

    # Optionally, save test coverage results (if using coverage)
    - name: Upload coverage results
      if: success()
      uses: codecov/codecov-action@v2