name: Run Tests

on:
  push:
    branches:
      - '*'  # Change to the branch you want to monitor, e.g., 'master', 'dev', etc.
  pull_request:
    branches:
      - '*'  # If you want tests to run on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "Geslo123"  # Hardcoded root password
          MYSQL_DATABASE: "user"  # Hardcoded database name
        ports:
          - 3306:3306  # Expose the MySQL port
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DB_HOST=localhost" >> $GITHUB_ENV  # Hardcoded MySQL host
        echo "DB_USER=root" >> $GITHUB_ENV  # Hardcoded MySQL user
        echo "DB_PASS=Geslo123" >> $GITHUB_ENV  # Hardcoded MySQL password
        echo "DB_NAME=user" >> $GITHUB_ENV  # Hardcoded database name
        echo "JWT_SECRET=e8694db72620093716a6c0a54ce7936e4bfc134da762595b7599092017c54872" >> $GITHUB_ENV  # Hardcoded JWT secret

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e 'SELECT 1'; do
          echo "Waiting for MySQL to be ready..."
          sleep 3
        done

    - name: Run tests
      run: |
        pytest
