name: Run Tests

on:
  push:
    branches:
      - main  # You can change this to your default branch, e.g., 'master'
  pull_request:
    branches:
      - main  # Trigger the workflow when there's a PR targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"  # You can change this to your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          pytest  # Make sure pytest is included in your requirements.txt

      # Optionally, you can upload test results to GitHub if you use a test reporting tool like pytest-cov
      - name: Upload Test Coverage Report
        if: success()
        uses: codecov/codecov-action@v2
