name: Run Tests

on:
  push:
    branches:
      - '*'  # Change to the branch you want to monitor, e.g., 'master', 'dev', etc.
  pull_request:
    branches:
      - '*'  # If you want tests to run on pull requests as well

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root_password  # Set the root password (adjust as needed)
          MYSQL_DATABASE: test_db  # The name of your test database
        ports:
          - 3306:3306  # Expose the MySQL port
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        until mysql -h 127.0.0.1 -u root -proot_password -e 'SELECT 1'; do
          echo "Waiting for MySQL to be ready..."
          sleep 3
        done

    - name: Run tests
      run: |
        pytest